import org.lwjgl.BufferUtils;
import org.lwjgl.LWJGLException;
import org.lwjgl.Sys;
import org.lwjgl.input.Keyboard;
import org.lwjgl.input.Mouse;
import org.lwjgl.opengl.Display;
import org.lwjgl.opengl.DisplayMode;
import org.lwjgl.opengl.EXTFramebufferObject;
import org.lwjgl.opengl.EXTTextureBufferObject;
import org.lwjgl.util.glu.GLU;
import org.newdawn.slick.Color;
import org.newdawn.slick.TrueTypeFont;
import org.newdawn.slick.opengl.InternalTextureLoader;
import org.newdawn.slick.opengl.Texture;
import org.newdawn.slick.opengl.TextureLoader;

import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.opengl.GL15.*;

import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.IOException;
import java.io.UTFDataFormatException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;

import javax.imageio.ImageIO;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String readFile( String path ){
        InputStream is = this.getClass().getResourceAsStream(path);
        java.util.Scanner s = new java.util.Scanner(is).useDelimiter("\\A");
        return s.hasNext() ? s.next() : "";
    }

    public String getGreeting() {
        return "Hello world.";
    }

    int WIDTH = 800, HEIGHT = 600;
    SimpleShader shader;

    public App(){
       try {
            Display.setDisplayMode(new DisplayMode( WIDTH, HEIGHT ));
            Display.setTitle("Episode 3 - OpenGL Rendering");
            Display.create();
        } catch (LWJGLException e) {
            e.printStackTrace();
            Display.destroy();
            System.exit(1);
        }


        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glFrustum(-.5,.5,-.5,.5,1,100000);

        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();


        TileSet rootTile = new TileSet(1,2,2, 16, "");

        shader = new SimpleShader(readFile("/Shader_v.glsl"),readFile("Shader_f.glsl"));
        shader.enable();

        while (!Display.isCloseRequested()) {

            //glClearColor(0.5f, 0.6f, 1.0f, 1.0f);;
            glClearColor(0.0f, 0.0f, 0.0f, 1.0f);;

            glDepthMask(true);
            glClear(GL_COLOR_BUFFER_BIT| GL_DEPTH_BUFFER_BIT);

            glLoadIdentity();

            glRotatef(90.0f, 1.0f, 0.0f, 0.0f);


            glTranslatef(0.0f, -1200.0f, 0.0f);
//            glRotatef(rx,-1.0f,0.0f,0f);

 //           glRotatef(ry,0f,1f,0f);


            rootTile.draw( );

            Display.update();
            Display.sync(60);
        }
        Display.destroy();
        System.exit(0);
    }

    public static void main(String[] args) {
        new App();
    }

}
